spring.application.name=AiSecurityLog
spring.mvc.problemdetails.enabled=true

# Server
server.port=${PORT:8080}

# Integração com a IA
ai.service.url=${AI_API_URL:http://127.0.0.1:8000/analisar}

# Banco de dados para conectar (comentado pois não é escopo do projeto porém caso queira integrar deixei um modelo)

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database=postgresql
# spring.datasource.url=${url}
# spring.datasource.username=${bancoUser}
# spring.datasource.password=${bancoSenha}
# spring.sql.init.mode=always

# swagger
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}
springdoc.open-api.info.title=Security Log AI
springdoc.open-api.info.description=Projeto analisador de log de cibersegurança com IA
springdoc.open-api.info.version=1.0.0
springdoc.open-api.info.contact.name=Izukill
springdoc.open-api.info.contact.url=https://github.com/Izukill/AiSecurityLog
springdoc.open-api.info.contact.email=luanloreto639@gmail.com
springdoc.open-api.info.license.name=Apache 2.0
springdoc.open-api.info.license.url=http://www.apache.org/licenses/LICENSE-2.0